# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperrecord',
            name='is_pre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperrecord',
            name='is_std',
            field=models.BooleanField(default=False),
        ),
    ]
